# Generated by Django 4.1.4 on 2023-01-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='user1.jpg', upload_to='images/'),
        ),
    ]
